const dbCard = [
  {
    id: 1,
    category: "Kamera",
    name: "Sony ZV-E10 II Mirrorless Camera Body Only (Black)",
    price: "16.999.000",
    promo: false,
    image: "/Products/sony-zv-e10.webp",
    description: "Kamera mirrorless compact dengan fitur unggulan untuk vlogging.",
  },
  {
    id: 2,
    category: "Kamera",
    name: "Canon EOS R50 Mirrorless Camera with RF-S18-45mm Lens (White)",
    price: "19.999.000",
    promo: true,
    image: "/Products/canon-eosr50.jpg",
    description: "Kamera mirrorless serbaguna dengan lensa RF-S 18-45mm.",
  },
  {
    id: 3,
    category: "Kamera",
    name: "Fujifilm X-T30 II Mirrorless Camera with XF18-55mm Lens (Silver)",
    price: "22.999.000",
    promo: true,
    image: "/Products/fuji-xt30.jpeg",
    description: "Kamera mirrorless ringan dengan desain klasik dan hasil foto berkualitas tinggi.",
  },
  {
    id: 4,
    category: "Aksesori Kamera",
    name: "SmallRig Camera Cage for Sony ZV-E10",
    price: "750.000",
    promo: false,
    image: "/Products/Smallrig-3538B-ZV-E10-Gage.w1200.webp",
    description: "Cage kamera untuk perlindungan dan fleksibilitas pemasangan aksesori.",
  },
  {
    id: 5,
    category: "Aksesori Kamera",
    name: "SanDisk Extreme PRO SDXC 128GB 200MB/s",
    price: "600.000",
    promo: false,
    image: "/Products/sandisk128gb.jpg",
    description: "Kartu memori berkecepatan tinggi untuk perekaman video 4K.",
  },
  {
    id: 6,
    category: "Aksesori Kamera",
    name: "Manfrotto Befree Advanced Aluminum Tripod",
    price: "2.900.000",
    promo: false,
    image: "/Products/manfrotto-befree-3-way.jpg",
    description: "Tripod aluminium portabel dengan stabilitas tinggi.",
  },
  {
    id: 7,
    category: "Gadget Pendukung",
    name: "MacBook Pro 14-inch M2 (512GB, 16GB RAM)",
    price: "28.999.000",
    promo: false,
    image: "/Products/MacbookPro-14inch.jpeg",
    description: "Laptop profesional dengan performa tinggi untuk video editing.",
  },
  {
    id: 8,
    category: "Gadget Pendukung",
    name: "Seagate One Touch Portable SSD 1TB",
    price: "2.200.000",
    promo: true,
    image: "/Products/seagate-one-touch-1tb.jpg",
    description: "Penyimpanan eksternal cepat dan portabel untuk file besar.",
  },
  {
    id: 9,
    category: "Gadget Pendukung",
    name: "Asus Vivobook Pro 16X OLED (Ryzen 7, 16GB, 1TB SSD)",
    price: "23.999.000",
    promo: false,
    image: "/Products/vivobook-pro-16xoled.jpg",
    description: "Laptop multimedia dengan layar OLED dan performa tinggi.",
  },
  {
    id: 10,
    category: "Gadget Pendukung",
    name: "Lenovo ThinkPad X1 Carbon Gen 11 (i7, 16GB, 512GB SSD)",
    price: "25.999.000",
    promo: false,
    image: "/Products/thinkpad-x1carbon.jpeg",
    description: "Laptop ringan dengan daya tahan baterai luar biasa untuk pekerjaan profesional.",
  },

  // Mikrofon dan Perangkat Audio
  {
    id: 11,
    category: "Mikrofon dan Audio",
    name: "Rode Wireless GO II Dual Channel Wireless Mic",
    price: "4.500.000",
    image: "/Products/WirelessGO2-large.jpg",
    description: "Sistem mikrofon nirkabel dual channel untuk perekaman profesional.",
  },
  {
    id: 12,
    category: "Mikrofon dan Audio",
    name: "BOYA BY-M1 Lavalier Microphone",
    price: "250.000",
    image: "/Products/BOYA-BY-M1lavalier.jpg",
    description: "Mikrofon lavalier yang ideal untuk wawancara dan presentasi.",
  },
  {
    id: 13,
    category: "Mikrofon dan Audio",
    name: "Zoom H1n Handy Recorder",
    price: "1.999.000",
    image: "/Products/zoom-h1nRecorder.jpeg",
    description: "Perekam audio portabel berkualitas tinggi untuk kebutuhan produksi konten.",
  },
  {
    id: 14,
    category: "Aksesori Kamera",
    name: "Godox SL60W LED Video Light",
    price: "1.800.000",
    promo: true,
    image: "/Products/godox-sl60w.jpeg",
    description: "Lampu video LED dengan pencahayaan terang dan stabil untuk produksi konten.",
  },
  {
    id: 15,
    category: "Mikrofon dan Audio",
    name: "Shure SM7B Vocal Dynamic Microphone",
    price: "6.000.000",
    promo: false,
    image: "/Products/shure-SM7B.jpeg",
    description: "Mikrofon dinamis berkualitas studio untuk perekaman vokal dan podcasting.",
  },
  {
    id: 16,
    category: "Kamera",
    name: "Panasonic Lumix GH6 Mirrorless Camera Body Only",
    price: "31.999.000",
    promo: false,
    image: "/Products/panasonic-lumix-gh6.png",
    description: "Kamera mirrorless unggulan dengan kemampuan video hingga 5.7K dan fitur stabilisasi canggih.",
  },
  {
    id: 17,
    category: "Kamera",
    name: "Nikon Z fc Mirrorless Camera with 16-50mm Lens (Silver)",
    price: "17.999.000",
    promo: true,
    image: "/Products/nikon-z-fc.webp",
    description: "Kamera mirrorless retro dengan kualitas gambar luar biasa dan lensa kit serbaguna.",
  },
  {
    id: 18,
    category: "Kamera",
    name: "Leica Q2 Full Frame Compact Camera (Black)",
    price: "89.999.000",
    promo: false,
    image: "/Products/leica-q2.jpeg",
    description: "Kamera compact premium dengan sensor full-frame dan lensa Leica Summilux 28mm f/1.7.",
  },
];
export default dbCard;